# Generated by Django 5.2.6 on 2025-09-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('product_description', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('Сапуни', 'Soaps'), ('Украси', 'Decorations'), ('Подаръчни комплекти', 'Gift sets')])),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
