# Generated by Django 5.2.6 on 2025-09-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0002_allproducts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allproducts',
            old_name='image',
            new_name='product_image',
        ),
    ]
