# Generated by Django 5.2.6 on 2025-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0003_rename_image_allproducts_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='product_type',
            field=models.CharField(choices=[('Сапуни', 'Сапуни'), ('Украси', 'Украси'), ('Подаръчни комплекти', 'Подаръчни комплекти')]),
        ),
    ]
