# Generated by Django 5.2.6 on 2025-10-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0004_alter_allproducts_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='second_product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
