# Generated by Django 5.2.6 on 2025-10-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0005_allproducts_second_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='applicable_for',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allproducts',
            name='first_long_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allproducts',
            name='second_long_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
