# Generated by Django 5.2.6 on 2025-11-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0009_alter_starrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starrating',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
    ]
