# Generated by Django 5.2.6 on 2025-11-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0010_alter_starrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='starrating',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='all_products.allproducts'),
            preserve_default=False,
        ),
    ]
