# Generated by Django 5.2.6 on 2025-11-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0012_boughtproducts'),
        ('cart', '0008_alter_orderusermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
