# Generated by Django 5.2.6 on 2025-11-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0014_alter_boughtproducts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_products.allproducts'),
        ),
    ]
