# Generated by Django 5.2.6 on 2025-11-27 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('address_email', models.EmailField(max_length=254)),
                ('town_name', models.CharField(max_length=100)),
                ('speedy_address', models.CharField(max_length=200)),
                ('user_finish_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image_cart', models.ImageField(upload_to='')),
                ('product_description_cart', models.CharField(max_length=200)),
                ('product_price_cart', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description_order_user', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('В процес', 'В процес'), ('Доставено', 'Доставено')], max_length=100)),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
