# Generated by Django 5.2.6 on 2025-10-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_product_remove_cart_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_image_cat',
            new_name='product_image_cart',
        ),
    ]
