# Generated by Django 5.2.6 on 2025-10-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_product_image_cat_cart_product_image_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='allproducts_ptr',
        ),
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
