# Generated by Django 5.2.6 on 2025-10-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_allproducts_ptr_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=100)),
                ('speedy_address', models.CharField(max_length=200)),
            ],
        ),
    ]
