# Generated by Django 5.2.6 on 2025-10-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_orderusermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderusermodel',
            name='status',
            field=models.CharField(choices=[('В процес', 'В процес'), ('Доставено', 'Доставено')], max_length=100),
        ),
    ]
