# Generated by Django 5.2.6 on 2025-11-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_orderusermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='first_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='last_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
