# Generated by Django 5.2.6 on 2025-11-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_addresses_email_addresses_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='email',
            new_name='address_email',
        ),
    ]
