# Generated by Django 5.2.6 on 2025-11-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_rename_email_addresses_address_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='address_email',
            field=models.EmailField(max_length=254),
        ),
    ]
